import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import HeaderBar from "@/components/HeaderBar";
import theme from "./theme";  // Import your custom theme
import { ThemeProvider, CssBaseline } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FlashBrain",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <ThemeProvider theme={theme}>
        <html lang="en">
          <CssBaseline />
          <body className={inter.className}>
            <HeaderBar />
            {children}
          </body>
        </html>
      </ThemeProvider>
    </ClerkProvider>

  );
}